title: T. H. Mercer
description: Speculative fiction and essays by T. H. Mercer.
url: "https://thmercer.com"
permalink: /:year/:slug/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: T. H. Mercer
  url: https://thmercer.com

social:
  name: T. H. Mercer
  links:
    - https://bsky.app/profile/thmercer.bsky.social
    - https://github.com/thmercer

exclude:
  - README.md
  - vendor
  - bin
